CREATE TABLE [dbo].[Person]
(
	[Id] INT NOT NULL PRIMARY KEY, 
    [Name] VARCHAR(50) NOT NULL, 
    [PhoneNumber] VARCHAR(50) NOT NULL, 
    [EMail] VARCHAR(50) NOT NULL,
    [EMail2] VARCHAR(50) NOT NULL
)
